In [1]:
import pandas as ps
from urllib.request import urlopen
import requests
url = "https://raw.githubusercontent.com/micybusy/sketch/main/charts.csv"
with urlopen(url) as f:
    content = ps.read_csv(url, encoding = "utf-8")
content["rankimportance"]=101-content["rank"]
content

,date,rank,song,artist,last-week,peak-rank,weeks-on-board,rankimportance
0,2021-11-06,1,Easy On Me,Adele,1.0,1,3,100
1,2021-11-06,2,Stay,The Kid LAROI & Justin Bieber,2.0,1,16,99
2,2021-11-06,3,Industry Baby,Lil Nas X & Jack Harlow,3.0,1,14,98
3,2021-11-06,4,Fancy Like,Walker Hayes,4.0,3,19,97
4,2021-11-06,5,Bad Habits,Ed Sheeran,5.0,2,18,96
...,...,...,...,...,...,...,...,...
330082,1958-08-04,96,Over And Over,Thurston Harris,NaN,96,1,5
330083,1958-08-04,97,I Believe In You,Robert & Johnny,NaN,97,1,4
330084,1958-08-04,98,Little Serenade,The Ames Brothers,NaN,98,1,3
330085,1958-08-04,99,I'll Get By (As Long As I Have You),Billy Williams,NaN,99,1,2
330086,1958-08-04,100,Judy,Frankie Vaughan,NaN,100,1,1

In [2]:
#entries_by_year = {}
#dummy_list = []
#a = 2022
#for i in range(0,len(content), 5200):
#    display(i)
#    dummy_list.append(content[i:i+5200])
#    entries_by_year.update({a:dummy_list})
#    a = a-1
#    dummy_list = []
#content

In [3]:
date=content['date'].str.split('-', expand=True)
date.rename(columns = {0:'year',1:'month',2:'day'}, inplace = True)
date["year"] = date.year.astype('int')
date["month"] = date.month.astype('int')
date["day"] = date.day.astype('int')
content["year"]=date["year"]
content["month"]=date["month"]
date

        year  month  day
0       2021     11    6
1       2021     11    6
2       2021     11    6
3       2021     11    6
4       2021     11    6
...      ...    ...  ...
330082  1958      8    4
330083  1958      8    4
330084  1958      8    4
330085  1958      8    4
330086  1958      8    4

[330087 rows x 3 columns]

In [4]:
#content["liste"]=1
#content['top_100'] = content.groupby(["artist", "song",'year'])['liste'].transform('sum')
#content=content.drop(["liste"],axis=1)

In [5]:
#content['control']=0
content.loc[(content["month"]>9),'year']=date['year']+1
#content['year']=content['year']+content['control']
#content=content.drop(["control"],axis=1)

In [6]:
a=content.loc[content["month"]==8]
a[:100]

,date,rank,song,artist,last-week,peak-rank,weeks-on-board,rankimportance,year,month
1000,2021-08-28,1,Stay,The Kid LAROI & Justin Bieber,1.0,1,6,100,2021,8
1001,2021-08-28,2,Bad Habits,Ed Sheeran,3.0,2,8,99,2021,8
1002,2021-08-28,3,Good 4 U,Olivia Rodrigo,2.0,1,14,98,2021,8
1003,2021-08-28,4,Rumors,Lizzo Featuring Cardi B,NaN,4,1,97,2021,8
1004,2021-08-28,5,Kiss Me More,Doja Cat Featuring SZA,4.0,3,19,96,2021,8
...,...,...,...,...,...,...,...,...,...,...
1095,2021-08-28,96,Next Girl,Carly Pearce,96.0,86,4,5,2021,8
1096,2021-08-28,97,I Like Dat,T-Pain & Kehlani,NaN,97,1,4,2021,8
1097,2021-08-28,98,Steal My Love,Dan + Shay,NaN,98,1,3,2021,8
1098,2021-08-28,99,Repeat It,Lil Tecca & Gunna,80.0,80,2,2,2021,8
1099,2021-08-28,100,5500 Degrees,"EST Gee Featuring Lil Baby, 42 Dugg & Rylo Rod...",NaN,92,2,1,2021,8

In [7]:
content['sumimportance'] = content.groupby(["artist", "song",'year'])['rankimportance'].transform('sum')
content=content.sort_values("sumimportance", ascending = False)
content[:55]

,date,rank,song,artist,last-week,peak-rank,weeks-on-board,rankimportance,year,month,sumimportance
7410,2020-06-06,11,Circles,Post Malone,10.0,1,39,90,2020,6,4848
10705,2019-10-19,6,Circles,Post Malone,7.0,4,6,95,2020,10,4848
7707,2020-05-16,8,Circles,Post Malone,8.0,1,36,93,2020,5,4848
6415,2020-08-15,16,Circles,Post Malone,20.0,1,49,85,2020,8,4848
8902,2020-02-22,3,Circles,Post Malone,3.0,1,24,98,2020,2,4848
8802,2020-02-29,3,Circles,Post Malone,3.0,1,25,98,2020,2,4848
10503,2019-11-02,4,Circles,Post Malone,4.0,4,8,97,2020,11,4848
6519,2020-08-08,20,Circles,Post Malone,18.0,1,48,81,2020,8,4848
8702,2020-03-07,3,Circles,Post Malone,3.0,1,26,98,2020,3,4848
8603,2020-03-14,4,Circles,Post Malone,3.0,1,27,97,2020,3,4848
6617,2020-08-01,18,Circles,Post Malone,20.0,1,47,83,2020,8,4848
6719,2020-07-25,20,Circles,Post Malone,13.0,1,46,81,2020,7,4848
6812,2020-07-18,13,Circles,Post Malone,13.0,1,45,88,2020,7,4848
10603,2019-10-26,4,Circles,Post Malone,6.0,4,7,97,2020,10,4848
6912,2020-07-11,13,Circles,Post Malone,10.0,1,44,88,2020,7,4848
8504,2020-03-21,5,Circles,Post Malone,4.0,1,28,96,2020,3,4848
8404,2020-03-28,5,Circles,Post Malone,5.0,1,29,96,2020,3,4848
9002,2020-02-15,3,Circles,Post Malone,3.0,1,23,98,2020,2,4848
7009,2020-07-04,10,Circles,Post Malone,13.0,1,43,91,2020,7,4848
10806,2019-10-12,7,Circles,Post Malone,8.0,4,5,94,2020,10,4848
7112,2020-06-27,13,Circles,Post Malone,11.0,1,42,88,2020,6,4848
8304,2020-04-04,5,Circles,Post Malone,5.0,1,30,96,2020,4,4848
8203,2020-04-11,4,Circles,Post Malone,5.0,1,31,97,2020,4,4848
7210,2020-06-20,11,Circles,Post Malone,11.0,1,41,90,2020,6,4848
8105,2020-04-18,6,Circles,Post Malone,4.0,1,32,95,2020,4,4848
8006,2020-04-25,7,Circles,Post Malone,6.0,1,33,94,2020,4,4848
7310,2020-06-13,11,Circles,Post Malone,11.0,1,40,90,2020,6,4848
10907,2019-10-05,8,Circles,Post Malone,9.0,4,4,93,2020,10,4848
7905,2020-05-02,6,Circles,Post Malone,7.0,1,34,95,2020,5,4848
7509,2020-05-30,10,Circles,Post Malone,10.0,1,38,91,2020,5,4848
7807,2020-05-09,8,Circles,Post Malone,6.0,1,35,93,2020,5,4848
7609,2020-05-23,10,Circles,Post Malone,8.0,1,37,91,2020,5,4848
6314,2020-08-22,15,Circles,Post Malone,16.0,1,50,86,2020,8,4848
10402,2019-11-09,3,Circles,Post Malone,4.0,3,9,98,2020,11,4848
9801,2019-12-21,2,Circles,Post Malone,2.0,1,15,99,2020,12,4848
6115,2020-09-05,16,Circles,Post Malone,16.0,1,52,85,2020,9,4848
9302,2020-01-25,3,Circles,Post Malone,3.0,1,20,98,2020,1,4848
9604,2020-01-04,5,Circles,Post Malone,3.0,1,17,96,2020,1,4848
5815,2020-09-26,16,Circles,Post Malone,16.0,1,55,85,2020,9,4848
5915,2020-09-19,16,Circles,Post Malone,15.0,1,54,85,2020,9,4848
9901,2019-12-14,2,Circles,Post Malone,1.0,1,14,99,2020,12,4848
9203,2020-02-01,4,Circles,Post Malone,3.0,1,21,97,2020,2,4848
10000,2019-12-07,1,Circles,Post Malone,1.0,1,13,100,2020,12,4848
6014,2020-09-12,15,Circles,Post Malone,16.0,1,53,86,2020,9,4848
9702,2019-12-28,3,Circles,Post Malone,2.0,1,16,98,2020,12,4848
10301,2019-11-16,2,Circles,Post Malone,3.0,2,10,99,2020,11,4848
9500,2020-01-11,1,Circles,Post Malone,5.0,1,18,100,2020,1,4848
6215,2020-08-29,16,Circles,Post Malone,15.0,1,51,85,2020,8,4848
9402,2020-01-18,3,Circles,Post Malone,1.0,1,19,98,2020,1,4848
9102,2020-02-08,3,Circles,Post Malone,4.0,1,22,98,2020,2,4848
10100,2019-11-30,1,Circles,Post Malone,2.0,1,12,100,2020,11,4848
10201,2019-11-23,2,Circles,Post Malone,2.0,2,11,99,2020,11,4848
19900,2018-01-13,1,Perfect,Ed Sheeran,1.0,1,19,100,2018,1,4526
21133,2017-10-21,34,Perfect,Ed Sheeran,58.0,34,6,67,2018,10,4526
17616,2018-06-23,17,Perfect,Ed Sheeran,21.0,1,42,84,2018,6,4526

In [8]:
content['rank_1']=0
content["rank_1"]=content["rank"].copy()
content["rank_1"]=content["rank_1"].apply(lambda x:  0 if x>1 else 1)
content['rank_1_sum'] = content.groupby(["artist", "song",'year'])['rank_1'].transform('sum')
content=content.sort_values("rank_1_sum", ascending = False)
content[:20]

,date,rank,song,artist,last-week,peak-rank,weeks-on-board,rankimportance,year,month,sumimportance,rank_1,rank_1_sum
13100,2019-05-04,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1.0,1,8,100,2019,5,2691,1,19
11204,2019-09-14,5,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,5.0,1,27,96,2019,9,2691,0,19
12300,2019-06-29,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1.0,1,16,100,2019,6,2691,1,19
13300,2019-04-20,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1.0,1,6,100,2019,4,2691,1,19
13200,2019-04-27,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1.0,1,7,100,2019,4,2691,1,19
13514,2019-04-06,15,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,32.0,15,4,86,2019,4,2691,0,19
13400,2019-04-13,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,15.0,1,5,100,2019,4,2691,1,19
11900,2019-07-27,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1.0,1,20,100,2019,7,2691,1,19
11403,2019-08-31,4,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,3.0,1,25,97,2019,8,2691,0,19
12600,2019-06-08,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1.0,1,13,100,2019,6,2691,1,19
11110,2019-09-21,11,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,5.0,1,28,90,2019,9,2691,0,19
13882,2019-03-16,83,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,NaN,83,1,18,2019,3,2691,0,19
11304,2019-09-07,5,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,4.0,1,26,96,2019,9,2691,0,19
11600,2019-08-17,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1.0,1,23,100,2019,8,2691,1,19
13631,2019-03-30,32,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,51.0,32,3,69,2019,3,2691,0,19
12700,2019-06-01,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1.0,1,12,100,2019,6,2691,1,19
12100,2019-07-13,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1.0,1,18,100,2019,7,2691,1,19
12200,2019-07-06,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1.0,1,17,100,2019,7,2691,1,19
11700,2019-08-10,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1.0,1,22,100,2019,8,2691,1,19
13000,2019-05-11,1,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,1.0,1,9,100,2019,5,2691,1,19

In [9]:
table=ps.DataFrame(content.groupby(['year','song','artist','sumimportance','rank_1_sum']).size().reset_index().rename(columns={0:'count'}))
table['ratio']=table['sumimportance']/table['count']
table=table.sort_values("sumimportance", ascending = False)
table[:25]

,year,song,artist,sumimportance,rank_1_sum,count,ratio
34373,2020,Circles,Post Malone,4848,3,52,93.230769
33367,2018,Perfect,Ed Sheeran,4526,5,52,87.038462
34228,2019,Without Me,Halsey,4480,2,50,89.600000
34130,2019,Sunflower (Spider-Man: Into The Spider-Verse),Post Malone & Swae Lee,4441,1,48,92.520833
30973,2014,Counting Stars,OneRepublic,4377,0,52,84.173077
35085,2021,Blinding Lights,The Weeknd,4357,0,48,90.770833
29059,2010,Need You Now,Lady Antebellum,4339,0,52,83.442308
30979,2014,Dark Horse,Katy Perry Featuring Juicy J,4336,4,52,83.384615
23661,1998,How Do I Live,LeAnn Rimes,4285,0,52,82.403846
24687,2000,Smooth,Santana Featuring Rob Thomas,4215,12,49,86.020408
33804,2019,Happier,Marshmello & Bastille,4198,0,47,89.319149
28423,2009,I'm Yours,Jason Mraz,4162,0,52,80.038462
31796,2015,Uptown Funk!,Mark Ronson Featuring Bruno Mars,4075,14,44,92.613636
27307,2007,Before He Cheats,Carrie Underwood,4010,0,52,77.115385
32435,2017,Closer,The Chainsmokers Featuring Halsey,3994,8,46,86.826087
35431,2021,Mood,24kGoldn Featuring iann dior,3975,8,46,86.413043
28494,2009,Love Story,Taylor Swift,3958,0,48,82.458333
28927,2010,"Hey, Soul Sister",Train,3882,0,50,77.640000
33292,2018,Meant To Be,Bebe Rexha & Florida Georgia Line,3881,0,47,82.574468
23888,1998,Truly Madly Deeply,Savage Garden,3875,2,43,90.116279
24445,2000,Breathe,Faith Hill,3865,0,48,80.520833
31775,2015,Thinking Out Loud,Ed Sheeran,3864,0,49,78.857143
34420,2020,Don't Start Now,Dua Lipa,3823,0,46,83.108696
30805,2013,Thrift Shop,Macklemore & Ryan Lewis Featuring Wanz,3818,6,48,79.541667
23224,1997,Foolish Games/You Were Meant For Me,Jewel,3792,0,44,86.181818

In [10]:
tabledate=ps.DataFrame(content.groupby(['year',"date"]).size().reset_index().rename(columns={0:'count'}))
tabledate=tabledate.drop(["count"],axis=1)
tabledatex=ps.DataFrame(tabledate.groupby(['year']).size().reset_index().rename(columns={0:'yeartotalweek'}))

In [11]:
tabledate["week"]=0
b=0

for i in range(65):
    a=tabledatex.iloc[i,1]
    for j in range(a):
         tabledate.iloc[j+b,2]=j+1
    b=b+a

In [12]:
tabledate=tabledate.drop(["year"],axis=1)
content=content.merge(tabledate,on=['date'], how='left')
content=content.merge(tabledatex,on=['year'], how='left')

In [13]:
content=content.sort_values(["date","rank"], ascending = True)

In [14]:
content["first_test"] = content.groupby(['year','song','artist'])["week"].transform("first")
content

,date,rank,song,artist,last-week,peak-rank,weeks-on-board,rankimportance,year,month,sumimportance,rank_1,rank_1_sum,week,yeartotalweek,first_test
10711,1958-08-04,1,Poor Little Fool,Ricky Nelson,NaN,1,1,100,1958,8,818,1,2,1,9,1
265314,1958-08-04,2,Patricia,Perez Prado And His Orchestra,NaN,2,1,99,1958,8,835,0,0,1,9,1
75447,1958-08-04,3,Splish Splash,Bobby Darin,NaN,3,1,98,1958,8,582,0,0,1,9,1
97335,1958-08-04,4,Hard Headed Woman,Elvis Presley With The Jordanaires,NaN,4,1,97,1958,8,509,0,0,1,9,1
272496,1958-08-04,5,When,Kalin Twins,NaN,5,1,96,1958,8,663,0,0,1,9,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148070,2021-11-06,96,To Be Loved By You,Parker McCollum,NaN,96,1,5,2022,11,5,0,0,6,6,6
175699,2021-11-06,97,Ain't Shit,Doja Cat,NaN,24,14,4,2022,11,9,0,0,6,6,4
112760,2021-11-06,98,Life Goes On,Oliver Tree,NaN,91,2,3,2022,11,13,0,0,6,6,4
40131,2021-11-06,99,Come Through,H.E.R. Featuring Chris Brown,NaN,64,16,2,2022,11,4,0,0,6,6,1
129218,2021-11-06,100,Nevada,YoungBoy Never Broke Again,NaN,58,4,1,2022,11,71,0,0,6,6,2

In [15]:
table=ps.DataFrame(content.groupby(['year','song','artist','sumimportance','rank_1_sum','yeartotalweek','first_test']).size().reset_index().rename(columns={0:'count'}))
table["debut"]=table["yeartotalweek"]-table["first_test"]+1
table['ratio']=table['sumimportance']/table['debut']
table=table.sort_values("ratio", ascending = False)
table[:25]

,year,song,artist,sumimportance,rank_1_sum,yeartotalweek,first_test,count,debut,ratio
23673,1998,I Don't Want To Miss A Thing,Aerosmith,400,4,52,49,4,4,100.000000
23257,1997,Honey,Mariah Carey,300,3,52,50,3,3,100.000000
22394,1995,Fantasy,Mariah Carey,100,1,53,53,1,1,100.000000
28399,2009,I Gotta Feeling,The Black Eyed Peas,1398,12,52,39,14,14,99.857143
34947,2020,WAP,Cardi B Featuring Megan Thee Stallion,598,4,52,47,6,6,99.666667
29033,2010,Love The Way You Lie,Eminem Featuring Rihanna,1195,7,52,41,12,12,99.583333
34425,2020,Dynamite,BTS,398,2,52,49,4,4,99.500000
31213,2014,Shake It Off,Taylor Swift,398,2,52,49,4,4,99.500000
35703,2021,Way 2 Sexy,Drake Featuring Future & Young Thug,199,1,52,51,2,2,99.500000
33218,2018,In My Feelings,Drake,1194,10,52,41,12,12,99.500000
35913,2022,Stay,The Kid LAROI & Justin Bieber,596,2,6,1,6,6,99.333333
22688,1995,You Are Not Alone,Michael Jackson,495,1,53,49,5,5,99.000000
31808,2015,What Do You Mean?,Justin Bieber,198,1,52,51,2,2,99.000000
23116,1997,4 Seasons Of Loneliness,Boyz II Men,99,0,52,52,1,1,99.000000
23285,1997,I'll Be Missing You,Puff Daddy & Faith Evans Featuring 112,1580,11,52,37,16,16,98.750000
35841,2022,Industry Baby,Lil Nas X & Jack Harlow,592,1,6,1,6,6,98.666667
35614,2021,Stay,The Kid LAROI & Justin Bieber,986,5,52,43,10,10,98.600000
28554,2009,Party In The U.S.A.,Miley Cyrus,492,0,52,48,5,5,98.400000
23355,1997,Mo Money Mo Problems,The Notorious B.I.G. Featuring Puff Daddy & Mase,885,2,52,44,9,9,98.333333
31914,2016,Cold Water,Major Lazer Featuring Justin Bieber & MO,688,0,52,46,7,7,98.285714
34087,2019,Senorita,Shawn Mendes & Camila Cabello,1277,1,52,40,13,13,98.230769
34608,2020,Laugh Now Cry Later,Drake Featuring Lil Durk,491,0,52,48,5,5,98.200000
33241,2018,Killshot,Eminem,98,0,52,52,1,1,98.000000
23852,1998,The Boy Is Mine,Brandy & Monica,1762,13,52,35,18,18,97.888889
32916,2017,Wild Thoughts,DJ Khaled Featuring Rihanna & Bryson Tiller,1272,0,53,41,13,13,97.846154

In [16]:
tablex=table.loc[table["year"]==2003]
tablex=tablex.sort_values("rank_1_sum", ascending = False)
tablex[:10]

,year,song,artist,sumimportance,rank_1_sum,yeartotalweek,first_test,count,debut,ratio
25788,2003,Lose Yourself,Eminem,2080,12,52,1,23,52,40.000000
25765,2003,In Da Club,50 Cent,2577,9,52,15,30,38,67.815789
25659,2003,Crazy In Love,Beyonce Featuring Jay Z,1769,8,52,34,19,19,93.105263
25864,2003,Shake Ya Tailfeather,"Nelly, P. Diddy & Murphy Lee",1157,4,52,39,14,14,82.642857
25586,2003,21 Questions,50 Cent Featuring Nate Dogg,1950,4,52,25,23,28,69.642857
25599,2003,All I Have,Jennifer Lopez Featuring LL Cool J,1876,4,52,13,21,40,46.900000
25704,2003,Get Busy,Sean Paul,2629,3,52,21,32,32,82.156250
25669,2003,Dilemma,Nelly Featuring Kelly Rowland,1469,3,52,1,17,52,28.250000
25937,2003,This Is The Night,Clay Aiken,800,2,52,39,14,14,57.142857
25592,2003,A Moment Like This,Kelly Clarkson,1152,2,52,1,18,52,22.153846

In [17]:
tablex=table.loc[table["year"]==2003]
tablex=tablex.sort_values("sumimportance", ascending = False)
tablex[:10]

,year,song,artist,sumimportance,rank_1_sum,yeartotalweek,first_test,count,debut,ratio
25968,2003,When I'm Gone,3 Doors Down,3380,0,52,8,45,45,75.111111
25763,2003,Ignition,R. Kelly,3177,0,52,6,42,47,67.595745
25918,2003,The Game Of Love,Santana Featuring Michelle Branch,2903,0,52,1,37,52,55.826923
25834,2003,Picture,Kid Rock Featuring Sheryl Crow Or Allison Moorer,2646,0,52,9,34,44,60.136364
25704,2003,Get Busy,Sean Paul,2629,3,52,21,32,32,82.156250
25765,2003,In Da Club,50 Cent,2577,9,52,15,30,38,67.815789
25805,2003,Miss You,Aaliyah,2529,0,52,9,30,44,57.477273
25631,2003,Bring Me To Life,Evanescence Featuring Paul McCoy,2369,0,52,24,29,29,81.689655
25954,2003,Unwell,matchbox twenty,2347,0,52,25,28,28,83.821429
25614,2003,Beautiful,Christina Aguilera,2242,0,52,8,27,45,49.822222

In [18]:
tablex=table.loc[table["year"]==2003]
tablex=tablex.sort_values("ratio", ascending = False)
tablex[:10]

,year,song,artist,sumimportance,rank_1_sum,yeartotalweek,first_test,count,debut,ratio
25659,2003,Crazy In Love,Beyonce Featuring Jay Z,1769,8,52,34,19,19,93.105263
25613,2003,Baby Boy,Beyonce Featuring Sean Paul,592,0,52,46,7,7,84.571429
25799,2003,Magic Stick,Lil' Kim Featuring 50 Cent,1933,0,52,30,23,23,84.043478
25954,2003,Unwell,matchbox twenty,2347,0,52,25,28,28,83.821429
25851,2003,Rock Wit U (Awww Baby),Ashanti,1742,0,52,32,21,21,82.952381
25769,2003,Into You,Fabolous Featuring Tamia Or Ashanti,1323,0,52,37,16,16,82.687500
25864,2003,Shake Ya Tailfeather,"Nelly, P. Diddy & Murphy Lee",1157,4,52,39,14,14,82.642857
25704,2003,Get Busy,Sean Paul,2629,3,52,21,32,32,82.156250
25631,2003,Bring Me To Life,Evanescence Featuring Paul McCoy,2369,0,52,24,29,29,81.689655
25814,2003,"Never Leave You - Uh Ooh, Uh Oooh!",Lumidee,1467,0,52,35,18,18,81.500000

In [19]:
def gettables(y, lines):
    tablex=table.loc[table["year"]==y]
    tablex=tablex.sort_values("ratio", ascending = False)
    tabley=tablex.sort_values("sumimportance", ascending = False)
    tablez = tablex.sort_values("rank_1_sum", ascending = False)
    tablex = tablex.reset_index();
    tabley = tabley.reset_index();
    tablez = tablez.reset_index();
    return {"ratio":tablex[:lines], "sumimp":tabley[:lines], "sum1": tablez[:lines]}

In [20]:
tablo = gettables(2019, 20)["ratio"]
tablo1 = gettables(2019, 20)["sumimp"]
tablo2 = gettables(2019, 20)["sum1"]
tablo["value"] = 0
tablo1["value"] = 0
tablo2["value"] = 0
tablo
for i in range(len(tablo)):
    tablo["value"][i] = len(tablo) - i
    tablo1["value"][i] = len(tablo) - i
    tablo2["value"][i] = len(tablo) - i
    
    
tablo["value"]=ps.to_numeric(tablo["value"])
tablo["value"] = tablo["value"]*0.25
tablo1["value"]=ps.to_numeric(tablo1["value"])
tablo1["value"] = tablo1["value"]*0.55
tablo2["value"]=ps.to_numeric(tablo2["value"])
tablo2["value"] = tablo2["value"]*0.2

<ipython-input-20-3a062d69f59c>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tablo["value"][i] = len(tablo) - i
<ipython-input-20-3a062d69f59c>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tablo1["value"][i] = len(tablo) - i
<ipython-input-20-3a062d69f59c>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tablo2["value"][i] = len(tablo) - i

In [21]:
evaluate = gettables(2019, 100)["sumimp"]
evaluate = evaluate.sort_values(by = "sumimportance", ascending = False)
evaluate["weight"] = float(0)
for i in range(len(evaluate)):
    for j in range(len(tablo)):
        if evaluate["song"][i] == tablo["song"][j]:
            evaluate["weight"][i] += float(tablo["value"][j])
    for k in range(len(tablo1)):
        if evaluate["song"][i] == tablo1["song"][k]:
            evaluate["weight"][i] += float(tablo1["value"][k])
    for l in range(len(tablo2)):
        if evaluate["song"][i] == tablo2["song"][l]:
            evaluate["weight"][i] += float(tablo2["value"][l])

<ipython-input-21-de49afae1319>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  evaluate["weight"][i] += float(tablo["value"][j])
<ipython-input-21-de49afae1319>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  evaluate["weight"][i] += float(tablo1["value"][k])
<ipython-input-21-de49afae1319>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  evaluate["weight"][i] += float(tablo2["value"][l])

In [25]:
evaluate = evaluate.sort_values(by = "weight", ascending = False)
evaluate = evaluate.reset_index()
evaluate

,level_0,index,year,song,artist,sumimportance,rank_1_sum,yeartotalweek,first_test,count,debut,ratio,weight
0,0,34228,2019,Without Me,Halsey,4480,2,52,3,50,50,89.600000,16.75
1,1,34130,2019,Sunflower (Spider-Man: Into The Spider-Verse),Post Malone & Swae Lee,4441,1,52,5,48,48,92.520833,15.45
2,3,34095,2019,Sicko Mode,Travis Scott,3755,1,52,1,45,52,72.211538,12.15
3,5,34233,2019,Wow.,Post Malone,3462,0,52,14,39,39,88.769231,10.75
4,2,33804,2019,Happier,Marshmello & Bastille,4198,0,52,1,47,52,80.730769,9.90
5,7,34088,2019,Shallow,Lady Gaga & Bradley Cooper,3358,1,52,2,45,51,65.843137,9.75
6,9,33781,2019,Girls Like You,Maroon 5 Featuring Cardi B,3069,6,52,1,35,52,59.019231,9.45
7,16,34000,2019,Old Town Road,Lil Nas X Featuring Billy Ray Cyrus,2691,19,52,24,29,29,92.793103,9.45
8,14,34126,2019,Sucker,Jonas Brothers,2701,1,52,24,29,29,93.137931,8.85
9,4,33816,2019,High Hopes,Panic! At The Disco,3748,0,52,1,45,52,72.076923,8.80
10,11,33587,2019,7 Rings,Ariana Grande,2863,8,52,18,33,35,81.800000,8.75
11,6,33748,2019,Eastside,"benny blanco, Halsey & Khalid",3453,0,52,1,42,52,66.403846,7.70
12,65,34087,2019,Senorita,Shawn Mendes & Camila Cabello,1277,1,52,40,13,13,98.230769,7.20
13,21,33625,2019,Bad Guy,Billie Eilish,2423,1,52,28,25,25,96.920000,7.15
14,8,33645,2019,Better,Khalid,3104,0,52,1,47,52,59.692308,6.60
15,10,33707,2019,Dancing With A Stranger,Sam Smith & Normani,2963,0,52,17,36,36,82.305556,6.00
16,35,34186,2019,Truth Hurts,Lizzo,1758,4,52,33,20,20,87.900000,4.70
17,34,33836,2019,I Don't Care,Ed Sheeran & Justin Bieber,1803,0,52,34,19,19,94.894737,4.50
18,12,33790,2019,Going Bad,Meek Mill Featuring Drake,2856,0,52,11,37,42,68.000000,4.40
19,78,33797,2019,Goodbyes,Post Malone Featuring Young Thug,1026,0,52,42,11,11,93.272727,4.00